sonar.projectKey=Devin-July_spring-data-requery
sonar.organization=devin-july
sonar.projectName=Spring Data Requery
sonar.projectVersion=2.0.3
sonar.host.url=https://sonarcloud.io
sonar.login=${SONARQUBE_TOKEN}
sonar.sources=.
sonar.exclusions=**/build/**,**/target/**,**/out/**,**/.gradle/**,**/node_modules/**,**/examples/**,**/doc/**
sonar.java.source=1.8
sonar.java.target=1.8
sonar.java.binaries=**/build/classes/**,**/target/classes/**
sonar.java.libraries=**/.gradle/caches/**/*.jar,**/build/libs/**/*.jar
